language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "arc-settings-panel:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: ILPOM9TnydjkRTw7Z0Kh2/A00cvr/G96VdgUaCoPlV5RqcZtBN2YaEyIAYWUHyMj2vZbNPfAOvkkavI8Hyng4FMZ+75ytjiQngfYdd8ceCPLUU7Avjn0Kz1elaXc0GEXfjSWgN/TXpEFmN0JLN1LeYP/zVmyKXTgkf6pB9ddfMluo1OLYq38T61IgP9QQ0oV7AnzmWo0pKVITNQwhfPNXCgSS3yiy4DVWDwdAbXTl6q1sHwQbMf5ktPYY0cLvRgXsYTqJEvQ3S3zOu4l30TtKC5ZKFbk1cgoaDFP0R2KRbA/HPzUiRhRafUBjygWrKCGQYvAdWLoECYAIMVVNTU6r49XsIxKYEsApsyQet5MFbavIcw0kmnkwPg85Y9hfnnMkzyRD52yMcwev5I4NsJ2PYIuw5y/CdrwWlSEZu5eoxyDpMzEJuc/lAncpm5zl+qFtasauBKa/g+J9TMSgiFwXF8YOv7Df0WPKIONM6JRBYtSq9yoqWgBh1PXEBqofUfRHju1AEsVDLMzA3xTzl9hnFLr6cQhJanMH8qP08HI/7NmmUYTLoJJ+N/b9Xm2jIZcqIHq6vA0wyGfHpBWiTXw4zZHzLI8hJ3sEQlbF7BGq+w1gRFWOdltrba6ETUEQfCVxEg6KDD/opJJoOZEeZymdZRTuQ1fLqaq98ale8ZKLyc=
  - secure: mCYpnHRPzZa8czfs5qgUuRcMfeFmU/faNjf3LvJqF8r0uaVVOTrqyKzfVfN9h3d6jhv4k4/kTe9L6Ks2yRR27TGtd+av6yudAVoSL18mkYnwzN/vNBcIULvR8iySgxelY/O/qaPWOKbmdLbA/9qU9tvIbvSx+0JHR6GR8Xq1k2q9JBasfGufdvlTVEdzSTXNA40PNhvdcOeQVZ9pl4o3QCWZix7lgJ1GpcwzlBboeemCqUR97DLJfSInPWmZ2YOJHaNKV0nO/DAbnE46JbWVWM3SIOBCAkLFEI1VxTcgQgnVHPkrQXe/30wd8GF2Bs2LGbF83+cCqE33HyjJyposcXKHezjj5svXjLrqg+87lBRgeeobSqO4dsTgWpRzhdfYFPWIq2Qn2/voB+PDsz2VXmh4wGdjO3U3z5LspnMM7lii1enmmZKoE8JLQ5CmOr7g1VtC33PbrkjPqfIm9L/jhAxRzYaD5UbLUaLrUF05ZmwB3AhhGUDg0TGU+yOl0eWMqzMosr2v7Lfy77dGkrFquCBgfL3+BLGf8zuzvSFNgugn4biWbko1O4HfziZw1Dq0qzxvpB++SGdTH61x6v61+80Lg2eFvdOZWnCF0BOo210Gy+4WHiueMT+9+iaQsN+z4BmE6PZ5rJBK9ZAYHvQp6SKafBZPsA3uxkPapZ8K5AY=
