/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-settings-panel.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {FlattenedNodesObserver} from '@polymer/polymer/lib/utils/flattened-nodes-observer.js';

import {ArcSettingsPanelMixin} from '@advanced-rest-client/arc-settings-panel-mixin/arc-settings-panel-mixin.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

export {ArcSettingsPanel};

declare namespace UiElements {

  /**
   * Settings panel for Advanced REST Client - electron app.
   *
   * It requires:
   *
   * - settings provider that handles `settings-read` and `settings-changed`
   * custom events
   * - all ARC models (required by data panel to clear data)
   */
  class ArcSettingsPanel extends
    ArcSettingsPanelMixin(
    Object) {

    /**
     * Currently selected settings panel.
     */
    selected: number|null|undefined;

    /**
     * When set it renders narrow view.
     * It replaces side navigation with paper tabs
     */
    narrow: boolean|null|undefined;

    /**
     * List of custom tabs added to the light DOM.
     */
    customTabs: any[]|null|undefined;

    /**
     * When set `systemVariables` options in request settings is disabled.
     * Chrome apps does not have this option.
     */
    systemVariablesDisabled: boolean|null|undefined;

    /**
     * A link to application privacy policy
     */
    privacyPolicyUrl: string|null|undefined;

    /**
     * When set REST APIs are supported in the application.
     */
    restApis: boolean|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _processValues(values: any): any;
    _setSettings(values: any): void;
    _processNewNodes(nodes: any): void;
    _processRemovedNodes(nodes: any): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "arc-settings-panel": UiElements.ArcSettingsPanel;
  }
}
