/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-settings-panel.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/utils/flattened-nodes-observer.d.ts" />
/// <reference path="../arc-request-settings-panel/arc-request-settings-panel.d.ts" />
/// <reference path="../arc-data-settings-panel/arc-data-settings-panel.d.ts" />
/// <reference path="../arc-privacy-settings-panel/arc-privacy-settings-panel.d.ts" />
/// <reference path="../arc-settings-panel-mixin/arc-settings-panel-mixin.d.ts" />
/// <reference path="../arc-view-settings-panel/arc-view-settings-panel.d.ts" />
/// <reference path="../paper-listbox/paper-listbox.d.ts" />
/// <reference path="../paper-item/paper-item.d.ts" />
/// <reference path="../iron-pages/iron-pages.d.ts" />
/// <reference path="../paper-tabs/paper-tabs.d.ts" />

declare namespace UiElements {

  /**
   * Settings panel for Advanced REST Client - electron app.
   *
   * It requires:
   *
   * - settings provider that handles `settings-read` and `settings-changed`
   * custom events
   * - all ARC models (required by data panel to clear data)
   */
  class ArcSettingsPanel extends
    ArcComponents.ArcSettingsPanelMixin(
    Object) {

    /**
     * Currently selected settings panel.
     */
    selected: number|null|undefined;

    /**
     * When set it renders narrow view.
     * It replaces side navigation with paper tabs
     */
    narrow: boolean|null|undefined;

    /**
     * List of custom tabs added to the light DOM.
     */
    customTabs: any[]|null|undefined;

    /**
     * When set `systemVariables` options in request settings is disabled.
     * Chrome apps does not have this option.
     */
    systemVariablesDisabled: boolean|null|undefined;

    /**
     * A link to application privacy policy
     */
    privacyPolicyUrl: string|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _processValues(values: any): any;
    _setSettings(values: any): void;
    _processNewNodes(nodes: any): void;
    _processRemovedNodes(nodes: any): void;
  }
}

interface HTMLElementTagNameMap {
  "arc-settings-panel": UiElements.ArcSettingsPanel;
}
