/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   data-settings-panel.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {DataSettingsPanel} from './src/DataSettingsPanel.js';
