/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ArcSettingsPanel.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, css} from 'lit-element';

import {ArcSettingsBase} from './ArcSettingsBase.js';

export {ArcSettingsPanel};

declare namespace UiElements {

  /**
   * Settings panel for Advanced REST Client - electron app.
   *
   * It requires:
   *
   * - settings provider that handles `settings-read` and `settings-changed`
   * custom events
   * - all ARC models (required by data panel to clear data)
   */
  class ArcSettingsPanel extends
    ArcSettingsPanelMixin(
    ArcSettingsBase) {

    /**
     * Currently selected settings panel.
     */
    selected: number|null|undefined;

    /**
     * When set it renders narrow view.
     * It replaces side navigation with paper tabs
     */
    narrow: boolean|null|undefined;

    /**
     * When set `systemVariables` options in request settings is disabled.
     * Chrome apps does not have this option.
     */
    systemVariablesDisabled: boolean|null|undefined;

    /**
     * A link to application privacy policy
     */
    privacyPolicyUrl: string|null|undefined;

    /**
     * When set REST APIs are supported in the application.
     */
    restApis: boolean|null|undefined;

    /**
     * When set it renders experiments tab for Electron app.
     */
    hasExperiments: boolean|null|undefined;
    constructor();
    render(): any;
    _setSettings(values: any): void;
    _processValues(values: any): any;
    _selectionHandler(e: any): void;
    _tabsTemplate(): any;
    _listTemplate(): any;
    _requestTemplate(): any;
    _dataTemplate(): any;
    _privacyTemplate(): any;
    _viewTemplate(): any;
    _experimentsTemplate(): any;
    _pageTemplate(): any;
  }
}
