/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/DataSettingsPanel.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, css} from 'lit-element';

import {ArcSettingsBase} from './ArcSettingsBase.js';

export {DataSettingsPanel};

declare class DataSettingsPanel extends ArcSettingsBase {
  constructor();
  connectedCallback(): void;
  render(): any;
  _deleteAllClick(): void;

  /**
   * Called when delete datastore dialog is closed.
   */
  _onClearDialogResult(e: any): void;
  _getSelectedDatabases(): any;

  /**
   * Handler to be called when the clear data dialog has been closed.
   * It it's not canceled then it will clear (destroy) selected datastores.
   */
  deleteDatabases(): Promise<any>|null;
  _exportAllFile(): void;
  _dataSettingsTemplate(): any;
  _exportTemplate(): any;
  _clearDataTemplate(): any;
}
