/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/PrivacySettingsPanel.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html} from 'lit-element';

import {ArcSettingsBase} from './ArcSettingsBase.js';

export {PrivacySettingsPanel};

declare class PrivacySettingsPanel extends ArcSettingsBase {
  constructor();
  render(): any;

  /**
   * Opens privacy policy in a new window.
   */
  openPrivacyPolicy(): void;
}
