/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ViewSettingsPanel.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html} from 'lit-element';

import {ArcSettingsBase} from './ArcSettingsBase.js';

export {ViewSettingsPanel};

declare class ViewSettingsPanel extends ArcSettingsBase {
  constructor();
  render(): any;

  /**
   * Dispatches `navigate` ebenmt to themes panel.
   */
  openThemesPanel(): void;
}
